# Generated by Django 3.2.4 on 2022-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(default='', max_length=500),
        ),
    ]
