# Generated by Django 3.2.4 on 2022-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('profile', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('twitter', models.CharField(max_length=40)),
                ('facebook', models.CharField(max_length=40)),
                ('instagram', models.CharField(max_length=40)),
                ('linkedin', models.CharField(max_length=40)),
            ],
        ),
    ]
