# Generated by Django 3.2.4 on 2022-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userdetail_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='about',
            field=models.TextField(max_length=200),
        ),
    ]
