# Generated by Django 3.2.4 on 2022-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_userdetail_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='facebook',
            field=models.CharField(default='#', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='instagram',
            field=models.CharField(default='#', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='job',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='linkedin',
            field=models.CharField(default='#', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='twitter',
            field=models.CharField(default='#', max_length=40),
        ),
    ]
