# Generated by Django 3.2.4 on 2022-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20220810_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
