# Generated by Django 3.2.4 on 2022-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_userdetail_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(default='guest', max_length=15),
        ),
    ]
