# Generated by Django 3.2.4 on 2022-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_userdetail_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
