# Generated by Django 3.2.4 on 2022-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_userdetail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='sex',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
