# Generated by Django 3.2.4 on 2022-08-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_cbtuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtuser',
            name='activeExam',
        ),
        migrations.RemoveField(
            model_name='cbtuser',
            name='completed',
        ),
    ]
