# Generated by Django 3.2.4 on 2022-08-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20220812_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbtExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('className', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('term', models.CharField(max_length=15)),
                ('key', models.CharField(max_length=30)),
                ('answered', models.CharField(max_length=500)),
                ('answers', models.CharField(max_length=200)),
            ],
        ),
    ]
