# Generated by Django 3.2.4 on 2022-08-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_cbtexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=2)),
                ('total', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('examiner', models.IntegerField()),
                ('first_ca', models.IntegerField()),
                ('second_ca', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('term', models.CharField(max_length=15)),
                ('key', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=500)),
                ('className', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cbtexam',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cbtuser',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
