# Generated by Django 3.2.4 on 2022-08-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_demoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoItem',
        ),
    ]
