# Generated by Django 3.2.4 on 2022-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_delete_demoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='amount',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
