# Generated by Django 3.2.4 on 2022-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_alter_userdetail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
