# Generated by Django 3.2.4 on 2022-08-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
    ]
