# Generated by Django 3.2.4 on 2022-08-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_area', '0004_auto_20220830_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
